"""Update time column for notes

Revision ID: 08c9fd4c7cad
Revises: 7fd14e85f36f
Create Date: 2020-05-08 16:21:13.847748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c9fd4c7cad'
down_revision = '7fd14e85f36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_note_update_time'), 'note', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_update_time'), table_name='note')
    op.drop_column('note', 'update_time')
    # ### end Alembic commands ###
