"""empty message

Revision ID: 7fd14e85f36f
Revises: cdf29c1f1bfa
Create Date: 2020-05-06 23:02:21.465729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd14e85f36f'
down_revision = 'cdf29c1f1bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_note_title'), 'note', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_title'), table_name='note')
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
