"""Tags table - adding unique property to name

Revision ID: a5a2726ef865
Revises: 1bcff6a26501
Create Date: 2020-05-10 18:43:18.281311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a2726ef865'
down_revision = '1bcff6a26501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_name', table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    # ### end Alembic commands ###
