"""Tags - added timestamp

Revision ID: d906a01f9e9f
Revises: a5a2726ef865
Create Date: 2020-05-11 16:16:36.212373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd906a01f9e9f'
down_revision = 'a5a2726ef865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tag_timestamp'), 'tag', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_timestamp'), table_name='tag')
    op.drop_column('tag', 'timestamp')
    # ### end Alembic commands ###
